- name: install psycopg2
  become: true
  package:
    name: python-psycopg2
    state: present

- name: create powa user
  become: true
  become_user: postgres
  postgresql_user:
    name: powa
    role_attr_flags: SUPERUSER,LOGIN
    password: powa
    encrypted: yes

- name: create powa database
  become: true
  become_user: postgres
  postgresql_db:
    name: powa
    owner: powa

- name: enable extensions for powa
  become: true
  become_user: postgres
  postgresql_ext:
    name: "{{ item }}"
    db: powa
  with_items:
    - pg_stat_statements
    - btree_gist
    - powa
    - pg_qualstats
    - pg_stat_kcache
    - hypopg
