- name: install pip
  become: true
  package:
    name: python-pip
    state: present

- name: install powa-web
  become: true
  pip:
    name: powa-web

- name: copy powa-web configuration
  become: true
  copy:
    src: powa-web.conf
    dest: /etc

- name: copy powa-web uwsgi configuration
  become: true
  copy:
    src: powa.ini
    dest: /etc/uwsgi/apps-enabled
  notify: uwsgi restart
