- name: copy powa-web configuration
  become: true
  copy:
    src: powa-web.conf
    dest: /etc

- name: copy powa-web uwsgi configuration
  become: true
  copy:
    src: powa.ini
    dest: /etc/uwsgi/apps-enabled
  notify: uwsgi restart
