- stat:
    path: /usr/lib/postgresql/9.6/lib/pg_qualstats.so
  register: pg_qualstats

- name: download pg_qualstats sources
  unarchive:
    src: https://github.com/dalibo/pg_qualstats/archive/1.0.2.tar.gz
    dest: /tmp
    remote_src: true
  when: pg_qualstats.stat.exists == False

- name: compiling pg_qualstats
  make:
    chdir: /tmp/pg_qualstats-1.0.2/
  when: pg_qualstats.stat.exists == False

- name: installing pg_qualstats
  become: true
  make:
    chdir: /tmp/pg_qualstats-1.0.2/
    target: install
  when: pg_qualstats.stat.exists == False

- name: remove sources
  file:
    path: /tmp/pg_qualstats-1.0.2/
    state: absent

- name: check configuration
  command: grep -q pg_qualstats /etc/postgresql/9.6/main/postgresql.conf
  register: result
  ignore_errors: True

- name: enable extension
  become: true
  become_user: postgres
  shell: pg_conftool set shared_preload_libraries "pg_qualstats,$(pg_conftool show --short shared_preload_libraries)"
  notify:
    - postgresql restart
  when: result|failed
