- name: install uwsgi
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: start uwsgi
  become: true
  service:
    name: uwsgi
    state: started
    enabled: yes
